### ISSUE TITLE
ampq refuses connection @localhost if port is remapped

### ISSUE THREAD

**Issue by mamunsardar** [docker-library/docs#1002]
`ampq` refuses connection is via `localhost` if `5672` port is remapped (for example `-p 56720:5672`). But it can connect using `docker container ip` as host.  But if I use `localhost` as host and change port to `56270`, I get error (Connection refused):  
docker-compose.yml:

```
version: "3"

services:

  app_rabbitmq:
    image: rabbitmq:3.6.10
    container_name: app_rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 56720:5672
      - 56722:15672
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  rabbitmq_data:
    external: false
```
