### ISSUE TITLE
rabbitmq docker container port is closed

### ISSUE THREAD

**Issue by behconsci** [docker-library/docs#1168]
![image](https://user-images.githubusercontent.com/10358323/37022636-db004880-2123-11e8-8503-9c74d0194b61.png)

even if I expose ports in docker compose file, my workers cannot reach the rabbitmq. here is the error message: 

`[2018-03-06 08:45:26,818: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.`

here is the rabbitmq in docker-compose file: 

```
rabbitmq:
    expose:
       - 5672
    volumes:
      - "/Users/data/myapp/rabbitmq:/var/lib/rabbitmq:rw"
    ports:
      - "5672:5672"
      - "15672:15672"
```

what am I doing wrong?
