### ISSUE TITLE
mongo authentication never success

### ISSUE THREAD

**Issue by guoxingx** [docker-library/docs#1220]
my docker compose file:

```
version: "3"
services:

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=name
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - ./data/mongo/db:/data/db
```

and docker logs shows user has been added success:

```
mongo_1  | Successfully added user: {
mongo_1  | 	"user" : "name",
mongo_1  | 	"roles" : [
mongo_1  | 		{
mongo_1  | 			"role" : "root",
mongo_1  | 			"db" : "admin"
mongo_1  | 		}
mongo_1  | 	]
mongo_1  | }
```

but I never made it through with authentication.

system: macOs 10.13.2
mongo image: latest
docker version: 18.03.1-ce
