### ISSUE TITLE
Impossible to set timezone

### ISSUE THREAD

**Issue by straumat** [docker-library/docs#1818]
I have this in my `docker-compose.yml` : 

```
  postgresql:
    image: library/postgres:13-alpine
    restart: always
    networks:
      - cassandre
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Paris
      - PGTZ=Europe/Paris
      - POSTGRES_DB=cassandre_trading_bot
      - POSTGRES_USER=cassandre_trading_bot
      - POSTGRES_PASSWORD=mypassword
```

But when I tun `docker-compose up`, it's two hours behind the computer time.  The other image in my docker compose have the right time : 

```
  postgresql-backup:
    image: prodrigestivill/postgres-backup-local:13-alpine
    depends_on:
      - postgresql
    restart: always
    networks:
      - cassandre
    volumes:
      - backup:/backups
    environment:
      - TZ=Europe/Paris
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=cassandre_trading_bot
      - POSTGRES_USER=cassandre_trading_bot
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_EXTRA_OPTS=-Z9
      - SCHEDULE=@every 0h10m0s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=3
      - HEALTHCHECK_PORT=8080
```
