### ISSUE TITLE
postgres:12.8 container not running

### ISSUE THREAD

**Issue by alexjpm** [docker-library/docs#2041]
Hi,

I'm having trouble running the postgres docker container since 24/09/2021 on circleci.

Using an Ubuntu 18.04.5 LTS instance, docker version 19.03.12, docker-compose version 1.29.1.  The only thing I can find that has changed is the postgres docker container.

docker compose yml file
```
services:
  db:
    container_name: db
    image: postgres:12.8
    environment:
      POSTGRES_USER: "****"
      POSTGRES_PASSWORD: "****"
      POSTGRES_DB: "****"
    ports:
      - 5432:5432
    networks:
      - circlenetwork
```

command:
```
env TARGET=target docker-compose -f docker-compose-circleci.yml run db
```

output:
```
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ERROR: 2
```

Can anyone suggest why this might be or steps I could take to try and fix?
