### ISSUE TITLE
Undocumented InfluxDB macro's INFLUXD_TLS_CERT and INFLUXD_TLS_KEY

### ISSUE THREAD

**Issue by Erriez** [docker-library/docs#2190]
Macro's `INFLUXD_TLS_CERT` and `INFLUXD_TLS_KEY` are missing in [README.md](https://github.com/docker-library/docs/blob/master/influxdb/README.md) to enable SSL.

`docker-compose.yml` example:

```yaml
version: '3'

services:
  influxdb:
    image: influxdb:2.4.0
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${NFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${NFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN}
      - INFLUXD_TLS_CERT=/ssl/finluxd.crt
      - INFLUXD_TLS_KEY=/ssl/finluxd.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_DIR}/influxdb2/data:/var/lib/influxdb2
      - ${VOLUME_DIR}/ssl:/ssl:ro
```
