### ISSUE TITLE
Please better instructions

### ISSUE THREAD

**Issue by ivose** [docker-library/docs#2305]
If i use docker-compose.yml:
```
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
And go to http://localhost:8080. What is username and password? admin/example? psql/example? nothing works.
Thank you
