### ISSUE TITLE
Request: adding Docker health check to `postgres/README.md`

### ISSUE THREAD

**Issue by jamesbraza** [docker-library/docs#2391]
It would be good to add a [`healthcheck`](https://docs.docker.com/compose/compose-file/compose-file-v3/) to the `postgres/README.md`.

There are some possible starting points posed here: https://stackoverflow.com/questions/65115627/safe-ways-to-specify-postgres-parameters-for-healthchecks-in-docker-compose

---

Aside: running the below:

```yaml
---
version: "3.8"
services:
    postgres:
        image: postgres:latest
        container_name: athena-postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
```

```bash
docker compose up postgres --detach 
docker compose run postgres pg_isready --username user --dbname db
```

I can never get `pg_isready` to output something besides `/var/run/postgresql:5432 - no response`

**Comment by LaurentGoderre** [comment]
The following works for me:

```
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
        healthcheck:
            test: pg_isready
            interval: 60s
            retries: 3
            start_period: 10s
            timeout: 10s
```

**Comment by jamesbraza** [comment]
@LaurentGoderre can you tell me what this outputs for you?

```bash
docker compose run postgres pg_isready
# or
docker compose run postgres pg_isready --username user --dbname db
```

**Comment by LaurentGoderre** [comment]
Running that command doesn't give you real result because you are overwriting the command so the postgres doesn't start.

A better way would be

```
docker run --name my-db  -e POSTGRES_PASSWORD=password -d postgres
sleep 2
docker exec my-db pg_isready
```

```
820871225dadb64bf79b128613e48a84224f2f53504164be989ce9cd770754fc
/var/run/postgresql:5432 - accepting connections
```

**Comment by jamesbraza** [comment]
Update, I have realized from https://docs.docker.com/engine/reference/builder/#healthcheck the default `interval` is 30-seconds.

So moving to:

```yaml
        healthcheck:
            test: pg_isready
            interval: 1s
```

This solved the issue:

```bash
>  time docker compose up --detach --wait postgres
...
docker compose up --detach --wait postgres  0.10s user 0.06s system 7% cpu 2.053 total
```
