### ISSUE TITLE
 [wordpress] Remove X-Powered-By: PHP/X

### ISSUE THREAD

**Issue by scmanjarrez** [docker-library/docs#2496]
Hi, is it possible to remove the Header X-Powered-By from the wordpress offered by docker? If so, how can I do that? This is my current compose:
```
 wordpress:
    image: wordpress
    restart: always
    volumes:
      - data:/var/www/html
    ports:
      - "127.0.0.1:${WP_PORT}:80"
    environment:
      - WORDPRESS_DB_USER=${SQL_USER}
      - WORDPRESS_DB_PASSWORD=${SQL_PASS}
      - WORDPRESS_DB_NAME=${SQL_DB}
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_TABLE_PREFIX=${PREFIX}
    depends_on:
      - mariadb
```
