### ISSUE TITLE
File/Folder permissions issues when using external volumes

### ISSUE THREAD

**Issue by NOTORIOUSVR** [docker-library/docs#2532]
I cannot seem to understand why when I use external volumes the web service has permission issues (cannot write).

The service should have full access, however it just doesn't work.

Can anyone let me know what I'm missing here?

```
version: "3.8"
services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - /nfs/docker_nfs/odoo/odoo-web-data:/var/lib/odoo
      - /nfs/docker_nfs/odoo/config:/etc/odoo
      - /nfs/docker_nfs/odoo/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=cqicLUxT9P
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=cqicLUxT9P
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /nfs/docker_nfs/odoo/odoo-db-data:/var/lib/postgresql/data/pgdata
```

permissions on the file server:

```
root@batcavefs[...E-2TB_MIRROR/DOCKER/DOCKER_STORE/odoo]# ls -l
total 10
drwxrwxr-x+  2 root  wheel   2 Jan 24 15:08 addons
drwxrwxr-x+  2 root  wheel   3 Jan 25 12:52 config
drwx------+ 19 999   wheel  26 Jan 25 13:03 odoo-db-data
drwxrwxr-x+  2 root  wheel   2 Jan 24 15:08 odoo-web-data
root@batcavefs[...E-2TB_MIRROR/DOCKER/DOCKER_STORE/odoo]#
```

attempting to create a file/directory from in the web docker shell:

```
odoo@e714c0d8b931:/$ cd /mnt/extra-addons/
odoo@e714c0d8b931:/mnt/extra-addons$ mkdir test
mkdir: cannot create directory 'test': Permission denied
odoo@e714c0d8b931:/mnt/extra-addons$ touch test
touch: cannot touch 'test': Permission denied
odoo@e714c0d8b931:/mnt/extra-addons$ 
```
