### ISSUE TITLE
[mysql] how to give parameters in docker-compose

### ISSUE THREAD

**Issue by Alber70g** [docker-library/docs#613]
How to set the parameters as mentioned here (https://github.com/docker-library/docs/tree/master/mysql#configuration-without-a-cnf-file) in the docker-compose.yml?

**Comment by tianon** [comment]
That'd be something like this:
```yaml
db:
  image: mysql:5.7
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  # or:
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  # (to ensure it translates from YAML to arguments properly the way you expect it to)
```
