### ISSUE TITLE
How to Run a systemd enabled app container in docker-compose?

### ISSUE THREAD

**Issue by goutham27** [docker-library/docs#741]
Hi,

I am able to run systemd enabled app container using below command 

`docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/c7-systemd-httpd`

How do I set **sys/fs/cgroup:/sys/fs/cgroup:ro** this inside docker-compose file ?

**Comment by tianon** [comment]
You'll want something like this:
```yaml
services:
    httpd:
        image: local/c7-systemd-httpd
...
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

In the future, general questions like this ought to be directed to the normal means of getting Docker help: https://docs.docker.com/opensource/get-help/ :+1:
