### ISSUE TITLE
Fatal error: Class 'mysqli' not found in - on line 19

### ISSUE THREAD

**Issue by Toshiwoz** [docker-library/docs#943]
Hi,
I am trying to run a new container using compose, and I am getting this message:
Fatal error: Class 'mysqli' not found in - on line 19

I am using docker compose, and till now it worked without a problem, is it due to recent changes? Maybe the new 4.8 version?

Here the (censored) compose file I use:

```yaml
version: '2'

services:
  wordpress:
    image: wordpress
    ports:
      - 8096:80
    volumes:
      - /persist/wordpress/xxx.xxxxxxx.xx/:/var/www/html/
      - /persist/wordpress/:/usr/local/etc/php/conf.d/
      - /persist/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    environment:
      - WORDPRESS_DB_PASSWORD=xxxxxxxxxx
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_NAME=wp_xx
      - WORDPRESS_TABLE_PREFIX=xxwp_
      - VIRTUAL_HOST=xxx.xxxxxxx.xx
      - LETSENCRYPT_HOST=xxx.xxxxxxx.xx
      - LETSENCRYPT_EMAIL=xxxxx@xxxxx.xx
    external_links:
      - mysql
    networks:
      - net_db
      - proxy

networks:
  net_db:
    external:
      name: dblayer_xxx
  proxy:
    external:
      name: proxy_xxx
```
